### PR TITLE
added a filters tab in the errors sidebar

### LINKED ISSUE #209: Implement filter by environment
We need to be able to filter by environment in our app. Some applications will want to filter errors by their staging/production or many review apps so we have to allow that.

### PR DESCRIPTION
**Pull request by Panioglo**
Fixes #209

---

This change is [Reviewable](https://reviewable.io/reviews/epiccoders/epiclogger/228)

### CODE REVIEW

**Comment by Chocksy** [comment]
Reviewed 9 of 9 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

_[app/assets/javascripts/pages/errors.js, line 26 [r1]](https://reviewable.io:443/reviews/epiccoders/epiclogger/228#-KOAGuKZPADmqS--2Zqt:-KOAGuKZPADmqS--2Zqu:172897862) ([raw file](https://github.com/epiccoders/epiclogger/blob/898b9bdbfcf58645aa771b56ae71cb7aacf1a8e5/app/assets/javascripts/pages/errors.js#L26)):_

> ``` JavaScript
>     window.location.href = uri;
>   });
> ```

We definitely don't want to do this. 100% against parsing urls and adding them like this. It seems more ok to me to just submit the form as you said it was happening.

---

_[app/controllers/errors_controller.rb, line 54 [r1]](https://reviewable.io:443/reviews/epiccoders/epiclogger/228#-KOAH25RanwLHCjPMZG1:-KOAH25RanwLHCjPMZG2:1369717061) ([raw file](https://github.com/epiccoders/epiclogger/blob/898b9bdbfcf58645aa771b56ae71cb7aacf1a8e5/app/controllers/errors_controller.rb#L54)):_

> ``` Ruby
>       if params[:intercom]
>         begin
>           current_website.intercom_integration.driver.send_message(params[:users], params[:message])
> ```

why the hell did you do this?

---

_[app/views/errors/_sidebar_filters.html.haml, line 32 [r1]](https://reviewable.io:443/reviews/epiccoders/epiclogger/228#-KOAHHRSrG0mi4tQ3imp:-KOAHHRSrG0mi4tQ3imq:-347899876) ([raw file](https://github.com/epiccoders/epiclogger/blob/898b9bdbfcf58645aa771b56ae71cb7aacf1a8e5/app/views/errors/_sidebar_filters.html.haml#L32)):_

> ``` Haml
>   /     %label.radio-inline
>   /       %input{:name => "status", :type => "radio"}>/
>   /       Resolved
> ```

Don't leave commented code in please.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/epiccoders/epiclogger/228)_

**Comment by Chocksy** [comment]
@Panioglo fix the specs also please!

**Comment by Panioglo** [comment]
Review status: 6 of 13 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

_[app/controllers/errors_controller.rb, line 54 [r1]](https://reviewable.io:443/reviews/epiccoders/epiclogger/228#-KOAH25RanwLHCjPMZG1:-KODwb-ddErl5OosECDI:-372510923) ([raw file](https://github.com/epiccoders/epiclogger/blob/898b9bdbfcf58645aa771b56ae71cb7aacf1a8e5/app/controllers/errors_controller.rb#L54)):_
<details><summary>

<i>Previously, Chocksy (Ciocanel Razvan) wrote…</i></summary>



> why the hell did you do this?
> </details>
> this is a mistake, I will explain it to you later

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/epiccoders/epiclogger/228)_

**Comment by Chocksy** [comment]
Reviewed 6 of 7 files at r2.
Review status: 12 of 13 files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

_[Gemfile, line 40 [r2]](https://reviewable.io:443/reviews/epiccoders/epiclogger/228#-KOF4mOC0bDKUOEWOMM4:-KOF4mODdZIKndM3FUpd:-887449515) ([raw file](https://github.com/epiccoders/epiclogger/blob/80116591045e7d080d11557ad271b10bf8bf551d/Gemfile#L40)):_

> ``` Ruby
> gem 'jquery-turbolinks'
> gem 'momentjs-rails'
> gem 'bootstrap3-datetimepicker-rails', '~> 4.14.30'
> ```

Let's use this instead of this gem: http://www.daterangepicker.com/

---

_[Gemfile.lock, line 485 [r2]](https://reviewable.io:443/reviews/epiccoders/epiclogger/228#-KOF4q3z3FFlGNpu9S4P:-KOF4q3z3FFlGNpu9S4Q:-969467667) ([raw file](https://github.com/epiccoders/epiclogger/blob/80116591045e7d080d11557ad271b10bf8bf551d/Gemfile.lock#L485)):_

> ``` Ruby
> 
> BUNDLED WITH
>    1.12.5
> ```

be careful and remove these lines from gemfile.lock when they are added.

---

_[app/assets/javascripts/pages/errors.js, line 21 [r2]](https://reviewable.io:443/reviews/epiccoders/epiclogger/228#-KOF4xZfZwDX79b4Q-ea:-KOF4xZfZwDX79b4Q-eb:-1149942930) ([raw file](https://github.com/epiccoders/epiclogger/blob/80116591045e7d080d11557ad271b10bf8bf551d/app/assets/javascripts/pages/errors.js#L21)):_

> ``` JavaScript
>   }
>   return uri
> }
> ```

please remove these i don't want regex for the simple search feature we want to add

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/epiccoders/epiclogger/228)_

**Comment by Panioglo** [comment]
Review status: 3 of 23 files reviewed at latest revision, 6 unresolved discussions.

---

_[app/assets/javascripts/pages/errors.js, line 26 [r1]](https://reviewable.io:443/reviews/epiccoders/epiclogger/228#-KOAGuKZPADmqS--2Zqt:-KOdkyauxSrPmPiUIHHv:b-896fix) ([raw file](https://github.com/epiccoders/epiclogger/blob/898b9bdbfcf58645aa771b56ae71cb7aacf1a8e5/app/assets/javascripts/pages/errors.js#L26)):_
<details><summary>

<i>Previously, Chocksy (Ciocanel Razvan) wrote…</i></summary>



> We definitely don't want to do this. 100% against parsing urls and adding them like this. It seems more ok to me to just submit the form as you said it was happening.
> </details>
> Done.

---

_[app/assets/javascripts/pages/errors.js, line 21 [r2]](https://reviewable.io:443/reviews/epiccoders/epiclogger/228#-KOF4xZfZwDX79b4Q-ea:-KOdkukbPFRfHUz96cwO:b-896fix) ([raw file](https://github.com/epiccoders/epiclogger/blob/80116591045e7d080d11557ad271b10bf8bf551d/app/assets/javascripts/pages/errors.js#L21)):_
<details><summary>

<i>Previously, Chocksy (Ciocanel Razvan) wrote…</i></summary>



> please remove these i don't want regex for the simple search feature we want to add
> </details>
> Done.

---

_[app/controllers/errors_controller.rb, line 54 [r1]](https://reviewable.io:443/reviews/epiccoders/epiclogger/228#-KOAH25RanwLHCjPMZG1:-KOdl4BOxii-sMvdGwtW:b-896fix) ([raw file](https://github.com/epiccoders/epiclogger/blob/898b9bdbfcf58645aa771b56ae71cb7aacf1a8e5/app/controllers/errors_controller.rb#L54)):_
<details><summary>

<i>Previously, Panioglo wrote…</i></summary>



> this is a mistake, I will explain it to you later
> </details>
> Done.

---

_[app/views/errors/_sidebar_filters.html.haml, line 32 [r1]](https://reviewable.io:443/reviews/epiccoders/epiclogger/228#-KOAHHRSrG0mi4tQ3imp:-KOdl6ri6VW_cNy3zHJs:b-896fix) ([raw file](https://github.com/epiccoders/epiclogger/blob/898b9bdbfcf58645aa771b56ae71cb7aacf1a8e5/app/views/errors/_sidebar_filters.html.haml#L32)):_
<details><summary>

<i>Previously, Chocksy (Ciocanel Razvan) wrote…</i></summary>



> Don't leave commented code in please.
> </details>
> Done.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/epiccoders/epiclogger/228)_

**Comment by Panioglo** [comment]
Review status: 3 of 23 files reviewed at latest revision, 6 unresolved discussions.

---

_[Gemfile.lock, line 485 [r2]](https://reviewable.io:443/reviews/epiccoders/epiclogger/228#-KOF4q3z3FFlGNpu9S4P:-KOdlRWhNKxJCXsztcoD:b-896fix) ([raw file](https://github.com/epiccoders/epiclogger/blob/80116591045e7d080d11557ad271b10bf8bf551d/Gemfile.lock#L485)):_
<details><summary>

<i>Previously, Chocksy (Ciocanel Razvan) wrote…</i></summary>



> be careful and remove these lines from gemfile.lock when they are added.
> </details>
> Done.

---

_[Gemfile, line 40 [r2]](https://reviewable.io:443/reviews/epiccoders/epiclogger/228#-KOF4mOC0bDKUOEWOMM4:-KOdlcWFwaPytYQNIwqN:b-896fix) ([raw file](https://github.com/epiccoders/epiclogger/blob/80116591045e7d080d11557ad271b10bf8bf551d/Gemfile#L40)):_
<details><summary>

<i>Previously, Chocksy (Ciocanel Razvan) wrote…</i></summary>



> Let's use this instead of this gem: http://www.daterangepicker.com/
> </details>
> Done.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/epiccoders/epiclogger/228)_

**Comment by Chocksy** [comment]
Reviewed 19 of 21 files at r3, 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

_[app/controllers/errors_controller.rb, line 26 [r4]](https://reviewable.io:443/reviews/epiccoders/epiclogger/228#-KOe6S-P_QkFZeKK5QpC:-KOe6S-P_QkFZeKK5QpD:b5go88w) ([raw file](https://github.com/epiccoders/epiclogger/blob/14d9da066f507ed34f3a8f1054a21b6f6e614819/app/controllers/errors_controller.rb#L26)):_

> ``` Ruby
>     errors = current_website.grouped_issues.order('last_seen DESC')
>     resolve if params[:commit] == 'Resolve'
>     unresolve if params[:commit] == 'Unresolve'
> ```

Why are you doing this here?

---

_[app/controllers/errors_controller.rb, line 32 [r4]](https://reviewable.io:443/reviews/epiccoders/epiclogger/228#-KOe7LYYzpbBXghVANrx:-KOe7LYYzpbBXghVANry:btv48ro) ([raw file](https://github.com/epiccoders/epiclogger/blob/14d9da066f507ed34f3a8f1054a21b6f6e614819/app/controllers/errors_controller.rb#L32)):_

> ``` Ruby
>       page = (position.to_f/errors_per_page).ceil
>       errors = errors.with_status(params[:status].to_sym) unless params[:status].blank?
>     elsif params[:commit] == 'search-button' && !params[:search].blank?
> ```

don't use ! just use present?

---

_[app/controllers/errors_controller.rb, line 34 [r4]](https://reviewable.io:443/reviews/epiccoders/epiclogger/228#-KOe6J27XNLig8ifGvjd:-KOe6J28kYlikCHYt1Gh:byvxwt4) ([raw file](https://github.com/epiccoders/epiclogger/blob/14d9da066f507ed34f3a8f1054a21b6f6e614819/app/controllers/errors_controller.rb#L34)):_

> ``` Ruby
>     elsif params[:commit] == 'search-button' && !params[:search].blank?
>       errors = matching_elements
>     elsif !params[:datepicker].blank?
> ```

`elsif params[:datepicker].present?`

---

_[app/views/errors/_error.html.haml, line 2 [r4]](https://reviewable.io:443/reviews/epiccoders/epiclogger/228#-KOe32XNMksNhh8G_AZ1:-KOe32XNMksNhh8G_AZ2:bp021ag) ([raw file](https://github.com/epiccoders/epiclogger/blob/14d9da066f507ed34f3a8f1054a21b6f6e614819/app/views/errors/_error.html.haml#L2)):_

> ``` Haml
> #grouped-issues.groups
>   = link_to error_url(id: error, tab: 'default') do
> ```

Why did you add id here?

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/epiccoders/epiclogger/228)_

**Comment by Panioglo** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

_[app/controllers/errors_controller.rb, line 26 [r4]](https://reviewable.io:443/reviews/epiccoders/epiclogger/228#-KOe6S-P_QkFZeKK5QpC:-KOe7yDHjR9krwignwbY:bq8ch4o) ([raw file](https://github.com/epiccoders/epiclogger/blob/14d9da066f507ed34f3a8f1054a21b6f6e614819/app/controllers/errors_controller.rb#L26)):_
<details><summary>

<i>Previously, Chocksy (Ciocanel Razvan) wrote…</i></summary>



> Why are you doing this here?
> </details>
> we get commit params == Resolve/Unresolve when we try to resolve or unresolve a group​.
> I used all these checks to keep the code ​clear

---

_[app/controllers/errors_controller.rb, line 32 [r4]](https://reviewable.io:443/reviews/epiccoders/epiclogger/228#-KOe7LYYzpbBXghVANrx:-KOe8y0kuPy2bgkM_4CT:b-7ulvj) ([raw file](https://github.com/epiccoders/epiclogger/blob/14d9da066f507ed34f3a8f1054a21b6f6e614819/app/controllers/errors_controller.rb#L32)):_
<details><summary>

<i>Previously, Chocksy (Ciocanel Razvan) wrote…</i></summary>



> don't use ! just use present?
> </details>
> .present? is more buggy than blank? cuz params[:search] can be equal to " ".. if param is a blank string.. present method still returns true

---

_[app/views/errors/_error.html.haml, line 2 [r4]](https://reviewable.io:443/reviews/epiccoders/epiclogger/228#-KOe32XNMksNhh8G_AZ1:-KOe9ez2g04kzvikyKmF:b-yt1440) ([raw file](https://github.com/epiccoders/epiclogger/blob/14d9da066f507ed34f3a8f1054a21b6f6e614819/app/views/errors/_error.html.haml#L2)):_
<details><summary>

<i>Previously, Chocksy (Ciocanel Razvan) wrote…</i></summary>



> Why did you add id here?
> </details>
> I will remove the id, the result will be the same

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/epiccoders/epiclogger/228)_

**Comment by Panioglo** [comment]
Review status: 22 of 23 files reviewed at latest revision, 4 unresolved discussions.

---

_[app/controllers/errors_controller.rb, line 34 [r4]](https://reviewable.io:443/reviews/epiccoders/epiclogger/228#-KOe6J27XNLig8ifGvjd:-KOeBGwZpV-JJ2O9FV8K:b-xz7f38) ([raw file](https://github.com/epiccoders/epiclogger/blob/14d9da066f507ed34f3a8f1054a21b6f6e614819/app/controllers/errors_controller.rb#L34)):_
<details><summary>

<i>Previously, Chocksy (Ciocanel Razvan) wrote…</i></summary>



> `elsif params[:datepicker].present?`
> </details>
> blank?  replaces (params[:datepicker].present? && params[:datepicker] != "" )

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/epiccoders/epiclogger/228)_

**Comment by Chocksy** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

_[app/controllers/errors_controller.rb, line 32 [r4]](https://reviewable.io:443/reviews/epiccoders/epiclogger/228#-KOe7LYYzpbBXghVANrx:-KOeDIFsPCBCJNaIAxiu:bu4ofnu) ([raw file](https://github.com/epiccoders/epiclogger/blob/14d9da066f507ed34f3a8f1054a21b6f6e614819/app/controllers/errors_controller.rb#L32)):_
<details><summary>

<i>Previously, Panioglo wrote…</i></summary>



> .present? is more buggy than blank? cuz params[:search] can be equal to " ".. if param is a blank string.. present method still returns true
> </details>
> present? is not buggy that's the way it should work :))

---

_[app/controllers/errors_controller.rb, line 34 [r4]](https://reviewable.io:443/reviews/epiccoders/epiclogger/228#-KOe6J27XNLig8ifGvjd:-KOeD8W0Oo_x5uc14Bx1:bd0umgm) ([raw file](https://github.com/epiccoders/epiclogger/blob/14d9da066f507ed34f3a8f1054a21b6f6e614819/app/controllers/errors_controller.rb#L34)):_
<details><summary>

<i>Previously, Panioglo wrote…</i></summary>



> blank?  replaces (params[:datepicker].present? && params[:datepicker] != "" )
> </details>
> I know what it does but i don't see how params[:datepicker] would be empty string. If you say it can then we can go with this code. I'll approve it.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/epiccoders/epiclogger/228#-:-KOeDXTafI02gSUQfCwL:bnfp4nl)_

**Pull request merged**
