### PR TITLE
Redirect after login, assign website if wrongly assigned & fill email for invites

### LINKED ISSUE #236: Fix error show action
If i visit an error url for another website than the current one, the error shows but the sidebar is for the current website. We need to change the current website if i can access that error and the error is for another one.

### PR DESCRIPTION
**Pull request by Panioglo**
Fixes #236 #237 #251 #253 #250 

---

This change is [Reviewable](https://reviewable.io/reviews/epiccoders/epiclogger/258)

### CODE REVIEW

**Comment by Chocksy** [comment]
Reviewed 9 of 9 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

_[app/controllers/application_controller.rb, line 55 [r1]](https://reviewable.io:443/reviews/epiccoders/epiclogger/258#-KPHgjZ8wSF-izbCpj0Z:-KPHgjZ8wSF-izbCpj0_:bn1tmy9) ([raw file](https://github.com/epiccoders/epiclogger/blob/bcfb3af0bbe957a219497b553688b091879400ef/app/controllers/application_controller.rb#L55)):_

> ``` Ruby
>   def redirect_if_needed
>     unless current_user
>       url_session(request.url) unless [root_url,"#{root_url}unauthenticated", login_url, signup_url].include? request.url.split('?').first
> ```

We should only save the url they are trying to access if the CanCan::AuthorizationNotPerformed exception is raised. You can see above there is a rescue_from. In there i would place the code to save the url. That way you don't need to check if the url is root or login or anything else because it will only save if there is no user logged in and the page is not public. Try to do that and then let's discuss.

---

_[app/controllers/application_controller.rb, line 67 [r1]](https://reviewable.io:443/reviews/epiccoders/epiclogger/258#-KPHgTuHo8X5jEBuNdu-:-KPHgTuHo8X5jEBuNdu0:b-pcfaap) ([raw file](https://github.com/epiccoders/epiclogger/blob/bcfb3af0bbe957a219497b553688b091879400ef/app/controllers/application_controller.rb#L67)):_

> ``` Ruby
> 
>   def after_login_redirect(url_to_redirect = nil)
>     redirect_to(url_to_redirect) && return unless url_to_redirect.nil?
> ```

we need to clear/remove the session[:url] value after it's first used. If we don't do that then when they try to login again it might redirect them without them wanting to do that.

---

_[app/controllers/users_controller.rb, line 15 [r1]](https://reviewable.io:443/reviews/epiccoders/epiclogger/258#-KPHfa78XQerGp3w6E8j:-KPHfa78XQerGp3w6E8k:b-l5348x) ([raw file](https://github.com/epiccoders/epiclogger/blob/bcfb3af0bbe957a219497b553688b091879400ef/app/controllers/users_controller.rb#L15)):_

> ``` Ruby
> 
>     invite = Invite.find_by_token(params[:token]) if params[:token]
>     @email = invite.email if invite
> ```

you are looking for token here but in the invites controller you don't seem to send it. 

---

_[app/views/errors/_sidebar_filters.html.haml, line 13 [r1]](https://reviewable.io:443/reviews/epiccoders/epiclogger/258#-KPHfzdgPt3OgNIPF0br:-KPHfzdgPt3OgNIPF0bs:b-gsn9sg) ([raw file](https://github.com/epiccoders/epiclogger/blob/bcfb3af0bbe957a219497b553688b091879400ef/app/views/errors/_sidebar_filters.html.haml#L13)):_

> ``` Haml
>       .form-group
>       %label Environment:
>       = select_tag 'env', options_for_select(current_website.unique_environments), prompt: "#{params[:env] || 'All environments'}", class: 'form-control'
> ```

setting prompt does not set the select value. If i click submit again this value won't be sent. Set the value not the prompt to the params.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/epiccoders/epiclogger/258)_

**Comment by Panioglo** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

_[app/controllers/application_controller.rb, line 55 [r1]](https://reviewable.io:443/reviews/epiccoders/epiclogger/258#-KPHgjZ8wSF-izbCpj0Z:-KPHzqsl4p5TjI86a26y:b-896fix) ([raw file](https://github.com/epiccoders/epiclogger/blob/bcfb3af0bbe957a219497b553688b091879400ef/app/controllers/application_controller.rb#L55)):_
<details><summary>

<i>Previously, Chocksy (Ciocanel Razvan) wrote…</i></summary>



> We should only save the url they are trying to access if the CanCan::AuthorizationNotPerformed exception is raised. You can see above there is a rescue_from. In there i would place the code to save the url. That way you don't need to check if the url is root or login or anything else because it will only save if there is no user logged in and the page is not public. Try to do that and then let's discuss.
> </details>
> Done.

---

_[app/controllers/application_controller.rb, line 67 [r1]](https://reviewable.io:443/reviews/epiccoders/epiclogger/258#-KPHgTuHo8X5jEBuNdu-:-KPHzyvskDKvQXCbnaeR:b-896fix) ([raw file](https://github.com/epiccoders/epiclogger/blob/bcfb3af0bbe957a219497b553688b091879400ef/app/controllers/application_controller.rb#L67)):_
<details><summary>

<i>Previously, Chocksy (Ciocanel Razvan) wrote…</i></summary>



> we need to clear/remove the session[:url] value after it's first used. If we don't do that then when they try to login again it might redirect them without them wanting to do that.
> </details>
> Done.

---

_[app/controllers/users_controller.rb, line 15 [r1]](https://reviewable.io:443/reviews/epiccoders/epiclogger/258#-KPHfa78XQerGp3w6E8j:-KPI-15QUE6F5Z5Y_8Iu:b-zh346e) ([raw file](https://github.com/epiccoders/epiclogger/blob/bcfb3af0bbe957a219497b553688b091879400ef/app/controllers/users_controller.rb#L15)):_
<details><summary>

<i>Previously, Chocksy (Ciocanel Razvan) wrote…</i></summary>



> you are looking for token here but in the invites controller you don't seem to send it. 
> </details>
> email is available on view under @email variable

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/epiccoders/epiclogger/258)_

**Comment by Chocksy** [comment]
Reviewed 5 of 5 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

_[app/controllers/sessions_controller.rb, line 14 [r2]](https://reviewable.io:443/reviews/epiccoders/epiclogger/258#-KPIAJHZjRW8kKRfVBfG:-KPIAJHZjRW8kKRfVBfH:bfg4zpl) ([raw file](https://github.com/epiccoders/epiclogger/blob/47546a5bf6142812edcad87b5c226ffd6e8e0629/app/controllers/sessions_controller.rb#L14)):_

> ``` Ruby
>     set_website(user.default_website)
>     after_login_redirect(url_session)
>     session.delete(:url) if session[:url]
> ```

this is not good. You need to remove the url from session no matter what. Each time we call after_login_redirect. Don't remove it just here.

---

_[app/controllers/users_controller.rb, line 15 [r1]](https://reviewable.io:443/reviews/epiccoders/epiclogger/258#-KPHfa78XQerGp3w6E8j:-KPIATlvwR3kHFOBbhky:b-71bpfm) ([raw file](https://github.com/epiccoders/epiclogger/blob/bcfb3af0bbe957a219497b553688b091879400ef/app/controllers/users_controller.rb#L15)):_
<details><summary>

<i>Previously, Panioglo wrote…</i></summary>



> email is available on view under @email variable
> </details>
> I was asking you about the token. Are you sure it's sent as a parameter? From what i see below the token is params[:id] ... Make sure that this works please.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/epiccoders/epiclogger/258)_

**Comment by Panioglo** [comment]
Review status: 8 of 11 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

_[app/controllers/sessions_controller.rb, line 14 [r2]](https://reviewable.io:443/reviews/epiccoders/epiclogger/258#-KPIAJHZjRW8kKRfVBfG:-KPIFIt_S4mhXE6RNUKt:b-896fix) ([raw file](https://github.com/epiccoders/epiclogger/blob/47546a5bf6142812edcad87b5c226ffd6e8e0629/app/controllers/sessions_controller.rb#L14)):_
<details><summary>

<i>Previously, Chocksy (Ciocanel Razvan) wrote…</i></summary>



> this is not good. You need to remove the url from session no matter what. Each time we call after_login_redirect. Don't remove it just here.
> </details>
> Done.

---

_[app/controllers/users_controller.rb, line 15 [r1]](https://reviewable.io:443/reviews/epiccoders/epiclogger/258#-KPHfa78XQerGp3w6E8j:-KPIF4rhoVimMdPXZTyg:b-wg4y2i) ([raw file](https://github.com/epiccoders/epiclogger/blob/bcfb3af0bbe957a219497b553688b091879400ef/app/controllers/users_controller.rb#L15)):_
<details><summary>

<i>Previously, Chocksy (Ciocanel Razvan) wrote…</i></summary>



> I was asking you about the token. Are you sure it's sent as a parameter? From what i see below the token is params[:id] ... Make sure that this works please.
> </details>
> yep, here is an example of the url: http://localhost:3000/signup?token=6lACn5sQIkM8VpF4gI2EgA

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/epiccoders/epiclogger/258)_

**Comment by Chocksy** [comment]
Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

_[spec/controllers/sessions_controller_spec.rb, line 64 [r2]](https://reviewable.io:443/reviews/epiccoders/epiclogger/258#-KPMjOM9nptHosOzY3ET:-KPMjOM9nptHosOzY3EU:b-g6fapo) ([raw file](https://github.com/epiccoders/epiclogger/blob/47546a5bf6142812edcad87b5c226ffd6e8e0629/spec/controllers/sessions_controller_spec.rb#L64)):_

> ``` Ruby
> 
>       expect(session[:url]).to be_nil
>     end
> ```

why did you remove this?

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/epiccoders/epiclogger/258)_

**Comment by Panioglo** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

_[spec/controllers/sessions_controller_spec.rb, line 64 [r2]](https://reviewable.io:443/reviews/epiccoders/epiclogger/258#-KPMjOM9nptHosOzY3ET:-KPMkJIhzonS8owmBIjp:bxeywaq) ([raw file](https://github.com/epiccoders/epiclogger/blob/47546a5bf6142812edcad87b5c226ffd6e8e0629/spec/controllers/sessions_controller_spec.rb#L64)):_
<details><summary>

<i>Previously, Chocksy (Ciocanel Razvan) wrote…</i></summary>



> why did you remove this?
> </details>
> well, it could have been left there, I thought we will add specs for the application_controller file

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/epiccoders/epiclogger/258)_

**Comment by Chocksy** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/epiccoders/epiclogger/258)_

**Pull request merged**
