### PR TITLE
added environment column to group

### LINKED ISSUE #244: Add environment column to group
- [x] add environment column to grouped_issues
- [x] filter by environment
- [x] clear the code and remove the old way we were retrieving environment

### PR DESCRIPTION
**Pull request by Panioglo**
Fixes #244

---

This change is [Reviewable](https://reviewable.io/reviews/epiccoders/epiclogger/245)

### CODE REVIEW

**Comment by Chocksy** [comment]
Reviewed 10 of 10 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

_[app/models/grouped_issue.rb, line 17 [r1]](https://reviewable.io:443/reviews/epiccoders/epiclogger/245#-KOi2cde-XpgRiBeUSns:-KOi2cdfJE41By_u_9Kg:b-57165g) ([raw file](https://github.com/epiccoders/epiclogger/blob/0b809fdca7bc563147776da1cb7c51cc91b702dd/app/models/grouped_issue.rb#L17)):_

> ``` Ruby
>   def first_issue
>     issues.first
>   end
> ```

why did you remove the first_issue method?

---

_[app/views/errors/_sidebar_filters.html.haml, line 22 [r1]](https://reviewable.io:443/reviews/epiccoders/epiclogger/245#-KOi2nCkIljbcG-uLRMd:-KOi2nCkIljbcG-uLRMe:bw54c91) ([raw file](https://github.com/epiccoders/epiclogger/blob/df0c7f644d7685e0c8a42f1f29830f666a6184f6/app/views/errors/_sidebar_filters.html.haml#L22)):_

> ``` Haml
>       %option{:value => 'review'} review
>       %option{:value => 'sandbox'} sandbox
>       %option{:value => 'staging'} Staging
> ```

this is not good. We don't want to make the env options as fixed values. We need to use the envs from the website. That can be done by doing a method in the website model and get the uniq values from the grouped_issues. We can also do `Rails.cache.fetch` to store the values in the cache system.

---

_[lib/tasks/environment.thor, line 12 [r1]](https://reviewable.io:443/reviews/epiccoders/epiclogger/245#-KOi8gLesAS0OoV6tmro:-KOi8gLfbVaGZmtHZnrn:b7cn620) ([raw file](https://github.com/epiccoders/epiclogger/blob/df0c7f644d7685e0c8a42f1f29830f666a6184f6/lib/tasks/environment.thor#L12)):_

> ``` Ruby
>       end
>     end
>     puts 'End. Success.'
> ```

Let's make a maintenance.thor file and place this method in because we will only run this once and never again. And it's good to have all of these methods in the maintenance file so we know what's in there.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/epiccoders/epiclogger/245)_

**Comment by Panioglo** [comment]
Review status: 8 of 12 files reviewed at latest revision, 3 unresolved discussions.

---

_[app/models/grouped_issue.rb, line 17 [r1]](https://reviewable.io:443/reviews/epiccoders/epiclogger/245#-KOi2cde-XpgRiBeUSns:-KOi9C8ljld5ymosjOMW:bhs21r4) ([raw file](https://github.com/epiccoders/epiclogger/blob/0b809fdca7bc563147776da1cb7c51cc91b702dd/app/models/grouped_issue.rb#L17)):_
<details><summary>

<i>Previously, Chocksy (Ciocanel Razvan) wrote…</i></summary>



> why did you remove the first_issue method?
> </details>
> it was used only in the environment method

---

_[app/views/errors/_sidebar_filters.html.haml, line 22 [r1]](https://reviewable.io:443/reviews/epiccoders/epiclogger/245#-KOi2nCkIljbcG-uLRMd:-KOk6FlJ8zcTAGvxTiKj:b-896fix) ([raw file](https://github.com/epiccoders/epiclogger/blob/df0c7f644d7685e0c8a42f1f29830f666a6184f6/app/views/errors/_sidebar_filters.html.haml#L22)):_
<details><summary>

<i>Previously, Chocksy (Ciocanel Razvan) wrote…</i></summary>



> this is not good. We don't want to make the env options as fixed values. We need to use the envs from the website. That can be done by doing a method in the website model and get the uniq values from the grouped_issues. We can also do `Rails.cache.fetch` to store the values in the cache system.
> </details>
> Done.

---

_[lib/tasks/environment.thor, line 12 [r1]](https://reviewable.io:443/reviews/epiccoders/epiclogger/245#-KOi8gLesAS0OoV6tmro:-KOk6Goz9uz8JvYCGqac:b-896fix) ([raw file](https://github.com/epiccoders/epiclogger/blob/df0c7f644d7685e0c8a42f1f29830f666a6184f6/lib/tasks/environment.thor#L12)):_
<details><summary>

<i>Previously, Chocksy (Ciocanel Razvan) wrote…</i></summary>



> Let's make a maintenance.thor file and place this method in because we will only run this once and never again. And it's good to have all of these methods in the maintenance file so we know what's in there.
> </details>
> Done.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/epiccoders/epiclogger/245)_

**Comment by Chocksy** [comment]
Reviewed 5 of 5 files at r2.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

_[app/models/website.rb, line 47 [r2]](https://reviewable.io:443/reviews/epiccoders/epiclogger/245#-KOk92TtJe94y--BKj6a:-KOk92TtJe94y--BKj6b:b-4do40q) ([raw file](https://github.com/epiccoders/epiclogger/blob/618caffff5703432346e6c76f2e6a5cb953d1966/app/models/website.rb#L47)):_

> ``` Ruby
>   def unique_environments
>     Rails.cache.fetch('unique_envs') do
>      grouped_issues.select('distinct environment').pluck(:environment).compact.uniq
> ```

there is no need for a uniq in here as distinct should only pick up the uniq envs. 

Also make sure that the indentation is correct here.

---

_[app/views/errors/_sidebar_filters.html.haml, line 9 [r2]](https://reviewable.io:443/reviews/epiccoders/epiclogger/245#-KOk9JbFSwDeWafRPK6p:-KOk9JbFSwDeWafRPK6q:b-gvw80l) ([raw file](https://github.com/epiccoders/epiclogger/blob/618caffff5703432346e6c76f2e6a5cb953d1966/app/views/errors/_sidebar_filters.html.haml#L9)):_

> ``` Haml
>             %span.glyphicon.glyphicon-search
>             Submit
>   - unless Rails.cache.read('unique_envs').blank?
> ```

Please remove this line.!! ... If you really want to check if there are no empty envs use the website.unique_environments method that's why we made it ... ...... ... :( :( :(

---

_[app/views/errors/_sidebar_filters.html.haml, line 13 [r2]](https://reviewable.io:443/reviews/epiccoders/epiclogger/245#-KOk9_6EUkGP5rAjUvMG:-KOk9_6EUkGP5rAjUvMH:b-nlvvop) ([raw file](https://github.com/epiccoders/epiclogger/blob/618caffff5703432346e6c76f2e6a5cb953d1966/app/views/errors/_sidebar_filters.html.haml#L13)):_

> ``` Haml
>       .form-group
>       %label Environment:
>       = select_tag 'env', options_for_select(Rails.cache.read('unique_envs')), prompt: 'All environments', class: 'form-control'
> ```

Same here why the hell do you think we made the method? Did you even read what fetch does?

---

_[app/views/errors/show.html.haml, line 3 [r2]](https://reviewable.io:443/reviews/epiccoders/epiclogger/245#-KOk9iEFJicFZMzmRnmh:-KOk9iEFJicFZMzmRnmi:b5j69yx) ([raw file](https://github.com/epiccoders/epiclogger/blob/618caffff5703432346e6c76f2e6a5cb953d1966/app/views/errors/show.html.haml#L3)):_

> ``` Haml
> .row
>   .col-sm-3#error-sidebar
>     - current_website.unique_environments
> ```

remove this please.

---

_[lib/tasks/maintenance.thor, line 1 [r2]](https://reviewable.io:443/reviews/epiccoders/epiclogger/245#-KOk9oWWC8JriIPSFMh1:-KOk9oWWC8JriIPSFMh2:b-pt9lxm) ([raw file](https://github.com/epiccoders/epiclogger/blob/618caffff5703432346e6c76f2e6a5cb953d1966/lib/tasks/maintenance.thor#L1)):_

> ``` Ruby
> class Environment < Thor
> ```

you forgot to rename the class name

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/epiccoders/epiclogger/245)_

**Comment by Panioglo** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

_[app/views/errors/_sidebar_filters.html.haml, line 9 [r2]](https://reviewable.io:443/reviews/epiccoders/epiclogger/245#-KOk9JbFSwDeWafRPK6p:-KOkCiR_GT-1JhEc9XrW:b-896fix) ([raw file](https://github.com/epiccoders/epiclogger/blob/618caffff5703432346e6c76f2e6a5cb953d1966/app/views/errors/_sidebar_filters.html.haml#L9)):_
<details><summary>

<i>Previously, Chocksy (Ciocanel Razvan) wrote…</i></summary>



> Please remove this line.!! ... If you really want to check if there are no empty envs use the website.unique_environments method that's why we made it ... ...... ... :( :( :(
> </details>
> Done.

---

_[app/views/errors/_sidebar_filters.html.haml, line 13 [r2]](https://reviewable.io:443/reviews/epiccoders/epiclogger/245#-KOk9_6EUkGP5rAjUvMG:-KOkCilmo30FwolJQjqc:b-896fix) ([raw file](https://github.com/epiccoders/epiclogger/blob/618caffff5703432346e6c76f2e6a5cb953d1966/app/views/errors/_sidebar_filters.html.haml#L13)):_
<details><summary>

<i>Previously, Chocksy (Ciocanel Razvan) wrote…</i></summary>



> Same here why the hell do you think we made the method? Did you even read what fetch does?
> </details>
> Done.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/epiccoders/epiclogger/245)_

**Comment by Panioglo** [comment]
Review status: 9 of 11 files reviewed at latest revision, 6 unresolved discussions.

---

_[app/models/website.rb, line 47 [r2]](https://reviewable.io:443/reviews/epiccoders/epiclogger/245#-KOk92TtJe94y--BKj6a:-KOn3DgerwbxNvgSwFet:b-896fix) ([raw file](https://github.com/epiccoders/epiclogger/blob/618caffff5703432346e6c76f2e6a5cb953d1966/app/models/website.rb#L47)):_
<details><summary>

<i>Previously, Chocksy (Ciocanel Razvan) wrote…</i></summary>



> there is no need for a uniq in here as distinct should only pick up the uniq envs. 
> 
> Also make sure that the indentation is correct here.
> </details>
> Done.

---

_[lib/tasks/maintenance.thor, line 1 [r2]](https://reviewable.io:443/reviews/epiccoders/epiclogger/245#-KOk9oWWC8JriIPSFMh1:-KOn3FRs6pOTFtoxv2eh:b-896fix) ([raw file](https://github.com/epiccoders/epiclogger/blob/618caffff5703432346e6c76f2e6a5cb953d1966/lib/tasks/maintenance.thor#L1)):_
<details><summary>

<i>Previously, Chocksy (Ciocanel Razvan) wrote…</i></summary>



> you forgot to rename the class name
> </details>
> Done.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/epiccoders/epiclogger/245)_

**Comment by Chocksy** [comment]
:lgtm:

---

Reviewed 1 of 5 files at r2, 5 of 5 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/epiccoders/epiclogger/245#-:-KOnLvzj3j7Rm4wnTorI:bnfp4nl)_

**Pull request merged**
