### PR TITLE
fixed case when we were saving an issue with the <no message> message

### LINKED ISSUE #225: There are some issues with the no message we save
The issue is that no message seems to be added for some other general errors. For example:
http://take.ms/jUE83

The error message belog is FB is not defined but the subject is still no message

### PR DESCRIPTION
**Pull request by Panioglo**
Fixes #225

---

This change is [Reviewable](https://reviewable.io/reviews/epiccoders/epiclogger/255)

### CODE REVIEW

**Comment by Chocksy** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

_[lib/error_store/error.rb, line 99 [r1]](https://reviewable.io:443/reviews/epiccoders/epiclogger/255#-KOoHbr5WwUk278Pw3xc:-KOoHbr5WwUk278Pw3xd:b-tjhgwf) ([raw file](https://github.com/epiccoders/epiclogger/blob/6f7f958830910f5b19ec53382aefa38b2192b291/lib/error_store/error.rb#L99)):_

> ``` Ruby
>       elsif data.key?(:exception)
>         data[:message] = "#{data[:exception][:values].first[:type]}: #{data[:exception][:values].first[:value]}"
>         data[:message] = '<no message>' if data[:message] == ': '
> ```

I have a problem with this because when we parse the exception we do some checks to make sure we get the right information. So i suggest you do this: 
1. set in error.rb the `data[:message] = nil` if there is no message defined
2. in manager.rb check if data[:message] is nil and if so check and get the value from the exception.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/epiccoders/epiclogger/255)_

**Comment by Chocksy** [comment]
Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_[lib/error_store/manager.rb, line 198 [r2]](https://reviewable.io:443/reviews/epiccoders/epiclogger/255#-KPHbh0YihiKYkzxq2kw:-KPHbh0ZmTQrY6MLLl0b:b-uohn3o) ([raw file](https://github.com/epiccoders/epiclogger/blob/8ba7e15808fcb8cf3c14c36d386fb8e2381b9302/lib/error_store/manager.rb#L198)):_

> ``` Ruby
>         message = '<no message>'
>       else
>         message = "#{hash.try(:[], :type)}: #{hash.try(:[], :value)}"
> ```

don't use try here as you are already checking this in the if above.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/epiccoders/epiclogger/255)_

**Comment by Panioglo** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

_[lib/error_store/error.rb, line 99 [r1]](https://reviewable.io:443/reviews/epiccoders/epiclogger/255#-KOoHbr5WwUk278Pw3xc:-KPI2eVkunU00oaI73nu:b-896fix) ([raw file](https://github.com/epiccoders/epiclogger/blob/6f7f958830910f5b19ec53382aefa38b2192b291/lib/error_store/error.rb#L99)):_
<details><summary>

<i>Previously, Chocksy (Ciocanel Razvan) wrote…</i></summary>



> I have a problem with this because when we parse the exception we do some checks to make sure we get the right information. So i suggest you do this: 
> 1. set in error.rb the `data[:message] = nil` if there is no message defined
> 2. in manager.rb check if data[:message] is nil and if so check and get the value from the exception.
>    </details>
>    Done.

---

_[lib/error_store/manager.rb, line 198 [r2]](https://reviewable.io:443/reviews/epiccoders/epiclogger/255#-KPHbh0YihiKYkzxq2kw:-KPI2b0jDLf6I7f7yuH3:bcfwsl4) ([raw file](https://github.com/epiccoders/epiclogger/blob/8ba7e15808fcb8cf3c14c36d386fb8e2381b9302/lib/error_store/manager.rb#L198)):_
<details><summary>

<i>Previously, Chocksy (Ciocanel Razvan) wrote…</i></summary>



> don't use try here as you are already checking this in the if above.
> </details>
> right :)

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/epiccoders/epiclogger/255)_

**Comment by Chocksy** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/epiccoders/epiclogger/255#-:-KPI9OuhtmqMRQAEhYmD:bnfp4nl)_

**Pull request merged**
